In [2]:
import numpy as np
import pandas as pd
import pickle as pkl
import json
import scipy.sparse as sp
import networkx as nx
from networkx.readwrite import json_graph
from datetime import datetime, timedelta
import time
import random
from collections import OrderedDict
import warnings; warnings.filterwarnings('ignore')

In [3]:
graphs = ['original', 'pred']
obj = []
for graph in graphs:
    with open('../data/'+graph +'.graph', 'r') as f:
        data = json.load(f)
    obj.append(data)
orig_g = json_graph.node_link_graph(obj[0])
pred_g = json_graph.node_link_graph(obj[1])
pd.DataFrame([[len(orig_g.nodes()),len(orig_g.edges())], [len(pred_g.nodes()),len(pred_g.edges())]],
             index=['original grapn', 'pred graph'], columns=['nodes', 'edges'])

                nodes  edges
original grapn    330   1564
pred graph        330   2199

### Degree centrality comparison

In [19]:
orig_degcen = nx.degree_centrality(orig_g)
orig_degcen_sorted = {k: v for k, v in sorted(orig_degcen.items(), key=lambda item: -item[1])}
pd.DataFrame(orig_degcen_sorted.items(), columns=['nodeid', 'degcen']).iloc[:10]

  nodeid    degcen
0   F42B  0.237082
1   B64D  0.191489
2   G01N  0.188450
3   F41H  0.185410
4   G01M  0.179331
5   G01S  0.173252
6   G06F  0.158055
7   B64C  0.145897
8   F41G  0.145897
9   G05D  0.130699

In [20]:
pred_degcen = nx.degree_centrality(pred_g)
pred_degcen_sorted = {k: v for k, v in sorted(pred_degcen.items(), key=lambda item: -item[1])}
pd.DataFrame(pred_degcen_sorted.items(), columns=['nodeid', 'degcen']).iloc[:10]

  nodeid    degcen
0   F42B  0.398176
1   G01N  0.373860
2   F41H  0.334347
3   B64D  0.310030
4   G01M  0.291793
5   H01M  0.279635
6   G01S  0.273556
7   B64C  0.255319
8   G06F  0.246201
9   F41G  0.224924

### Betweenness centrality comparison

In [21]:
orig_betcen = nx.betweenness_centrality(orig_g)
orig_betcen_sorted = {k: v for k, v in sorted(orig_betcen.items(), key=lambda item: -item[1])}
pd.DataFrame(orig_betcen_sorted.items(), columns=['nodeid', 'degcen']).iloc[:10]

  nodeid    degcen
0   G01N  0.115577
1   F42B  0.114205
2   F41H  0.095198
3   B64D  0.052794
4   H01M  0.048182
5   G01M  0.044467
6   F41F  0.042450
7   G01S  0.039170
8   B64C  0.037595
9   B01J  0.035983

In [22]:
pred_betcen = nx.betweenness_centrality(pred_g)
pred_betcen_sorted = {k: v for k, v in sorted(pred_betcen.items(), key=lambda item: -item[1])}
pd.DataFrame(pred_betcen_sorted.items(), columns=['nodeid', 'degcen']).iloc[:10]

  nodeid    degcen
0   G01N  0.129017
1   F42B  0.114937
2   F41H  0.085824
3   B01J  0.043761
4   B64D  0.043576
5   H01M  0.042591
6   F41F  0.042579
7   G01M  0.037293
8   G01S  0.036696
9   G06F  0.028230

### Closness centrality comparison

In [24]:
orig_clscen = nx.closeness_centrality(orig_g)
orig_clscen_sorted = {k: v for k, v in sorted(orig_clscen.items(), key=lambda item: -item[1])}
pd.DataFrame(orig_clscen_sorted.items(), columns=['nodeid', 'degcen']).iloc[:10]

  nodeid    degcen
0   F42B  0.479083
1   B64D  0.460532
2   F41H  0.456688
3   G01N  0.455927
4   G01M  0.453659
5   B64C  0.443365
6   G01S  0.441220
7   F41G  0.440509
8   G06F  0.435599
9   H01M  0.422807

In [25]:
pred_clscen = nx.closeness_centrality(pred_g)
pred_clscen_sorted = {k: v for k, v in sorted(pred_clscen.items(), key=lambda item: -item[1])}
pd.DataFrame(pred_clscen_sorted.items(), columns=['nodeid', 'degcen']).iloc[:10]

  nodeid    degcen
0   F42B  0.559420
1   G01N  0.552639
2   F41H  0.534290
3   B64D  0.524054
4   G01M  0.517120
5   H01M  0.509416
6   G01S  0.508469
7   B64C  0.499190
8   G06F  0.497375
9   F41G  0.487623